#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : i2c-tools
Version  : 4.0
Release  : 8
URL      : https://www.kernel.org/pub/software/utils/i2c-tools/i2c-tools-4.0.tar.gz
Source0  : https://www.kernel.org/pub/software/utils/i2c-tools/i2c-tools-4.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: i2c-tools-bin
Requires: i2c-tools-lib
Requires: i2c-tools-doc
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
I2C TOOLS FOR LINUX
===================
This package contains an heterogeneous set of I2C tools for the Linux kernel
as well as an I2C library. The tools were originally part of the lm-sensors
project but were finally split into their own package for convenience. The
library is used by some of the tools, but can also be used by third-party
applications. The tools and library compile, run and have been tested on
GNU/Linux.

%package bin
Summary: bin components for the i2c-tools package.
Group: Binaries

%description bin
bin components for the i2c-tools package.


%package dev
Summary: dev components for the i2c-tools package.
Group: Development
Requires: i2c-tools-lib
Requires: i2c-tools-bin
Provides: i2c-tools-devel

%description dev
dev components for the i2c-tools package.


%package doc
Summary: doc components for the i2c-tools package.
Group: Documentation

%description doc
doc components for the i2c-tools package.


%package lib
Summary: lib components for the i2c-tools package.
Group: Libraries

%description lib
lib components for the i2c-tools package.


%prep
%setup -q -n i2c-tools-4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1526059628
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1526059628
rm -rf %{buildroot}
%make_install prefix=/usr

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ddcmon
/usr/bin/decode-dimms
/usr/bin/decode-edid
/usr/bin/decode-vaio
/usr/bin/i2c-stub-from-dump
/usr/bin/i2cdetect
/usr/bin/i2cdump
/usr/bin/i2cget
/usr/bin/i2cset
/usr/bin/i2ctransfer

%files dev
%defattr(-,root,root,-)
/usr/include/i2c/smbus.h
/usr/lib/libi2c.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib/libi2c.so.0
/usr/lib/libi2c.so.0.1.0
