#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : i2c-tools
Version  : 4.3
Release  : 15
URL      : https://git.kernel.org/pub/scm/utils/i2c-tools/i2c-tools.git/snapshot/i2c-tools-4.3.tar.gz
Source0  : https://git.kernel.org/pub/scm/utils/i2c-tools/i2c-tools.git/snapshot/i2c-tools-4.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: i2c-tools-bin = %{version}-%{release}
Requires: i2c-tools-lib = %{version}-%{release}
Requires: i2c-tools-license = %{version}-%{release}
Requires: i2c-tools-man = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
I2C TOOLS FOR LINUX
===================
This package contains an heterogeneous set of I2C tools for the Linux kernel
as well as an I2C library. The tools were originally part of the lm-sensors
project but were finally split into their own package for convenience. The
library is used by some of the tools, but can also be used by third-party
applications. The tools and library compile, run and have been tested on
GNU/Linux.

%package bin
Summary: bin components for the i2c-tools package.
Group: Binaries
Requires: i2c-tools-license = %{version}-%{release}

%description bin
bin components for the i2c-tools package.


%package dev
Summary: dev components for the i2c-tools package.
Group: Development
Requires: i2c-tools-lib = %{version}-%{release}
Requires: i2c-tools-bin = %{version}-%{release}
Provides: i2c-tools-devel = %{version}-%{release}
Requires: i2c-tools = %{version}-%{release}

%description dev
dev components for the i2c-tools package.


%package lib
Summary: lib components for the i2c-tools package.
Group: Libraries
Requires: i2c-tools-license = %{version}-%{release}

%description lib
lib components for the i2c-tools package.


%package license
Summary: license components for the i2c-tools package.
Group: Default

%description license
license components for the i2c-tools package.


%package man
Summary: man components for the i2c-tools package.
Group: Default

%description man
man components for the i2c-tools package.


%prep
%setup -q -n i2c-tools-4.3
cd %{_builddir}/i2c-tools-4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1626995942
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1626995942
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/i2c-tools
cp %{_builddir}/i2c-tools-4.3/COPYING %{buildroot}/usr/share/package-licenses/i2c-tools/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/i2c-tools-4.3/COPYING.LGPL %{buildroot}/usr/share/package-licenses/i2c-tools/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install PREFIX=/usr libdir=/usr/lib64
## Remove excluded files
rm -f %{buildroot}/usr/include/linux/i2c-dev.h

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ddcmon
/usr/bin/decode-dimms
/usr/bin/decode-edid
/usr/bin/decode-vaio
/usr/bin/i2c-stub-from-dump
/usr/bin/i2cdetect
/usr/bin/i2cdump
/usr/bin/i2cget
/usr/bin/i2cset
/usr/bin/i2ctransfer

%files dev
%defattr(-,root,root,-)
/usr/include/i2c/smbus.h
/usr/lib64/libi2c.so
/usr/share/man/man3/libi2c.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libi2c.so.0
/usr/lib64/libi2c.so.0.1.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/i2c-tools/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/i2c-tools/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/decode-dimms.1
/usr/share/man/man1/decode-vaio.1
/usr/share/man/man8/i2c-stub-from-dump.8
/usr/share/man/man8/i2cdetect.8
/usr/share/man/man8/i2cdump.8
/usr/share/man/man8/i2cget.8
/usr/share/man/man8/i2cset.8
/usr/share/man/man8/i2ctransfer.8
